apiVersion: v1
kind: Pod
metadata:
  name: demo-restart-never
  namespace: sit722
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox
      command: ["sh","-c","echo 'This will exit with 1' && exit 1"]
