apiVersion: v1
kind: Pod
metadata:
  name: acr-test
spec:
  containers:
  - name: acr-test
    image: sit722ruddy95586acr.azurecr.io/week05-frontend:latest    
    command: [ "sleep" ]
    args: [ "3600" ]
  restartPolicy: Never
