apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-w05-aks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: ruddy/customer-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@customer-db-service-w05-aks:5432/customerdb
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP
