apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-w05-aks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-w05-aks
  template:
    metadata:
      labels:
        app: frontend-w05-aks
    spec:
      containers:
        - name: frontend
          image: sit722ruddy95586acr.azurecr.io/week05-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend-w05-aks
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: NodePort
