apiVersion: v1
kind: Secret
metadata:
  name: ecomm-secrets-w05-aks
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  RABBITMQ_USER: Z3Vlc3Q=
  RABBITMQ_PASS: Z3Vlc3Q=
  AZURE_STORAGE_ACCOUNT_NAME: c2l0NzIyc3RvcmFnZXJ1ZGR5
  AZURE_STORAGE_ACCOUNT_KEY:  ZnJza240RlVQZlRxMzdqdGpOeFpINkFRMDV0THduVUM4NTg0cWhmTmF2NCsvMUJ1eURmd2lVV2JsK1ZWNTR3UzloZXdCNWFqNUZDeCtBU3QvUWx0VEE9PQ==
